# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndArchive
  displayName: 'Build and Archive Vue App'
  steps:
  - checkout: self
    fetchDepth: 1

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: 'coding-fundi-nuxt'
      verbose: false

  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: custom
      workingDir: 'coding-fundi-nuxt'
      verbose: false
      customCommand: 'run build'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: drop'
    inputs:
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
